export const ActionType = {
    SET_PRODUCT : "SET_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    SEARCH_PRODUCT : "SEARCH_PRODUCT",
    QUESTION_PRODUCT : "QUESTION_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    VENDOR_SUCCESS: "VENDOR_SUCCESS",
    VENDOR_FAIL: "VENDOR_FAIL",
}